    1 #! /usr/bin/env python
    2 #  -*- coding: utf-8 -*-
    3 #
    4 # GUI module generated by PAGE version 6.0.1
    5 #  in conjunction with Tcl version 8.6
    6 #    Jan 09, 2021 03:23:57 PM EST  platform: Windows NT
    7 
    8 import sys
    9 
   10 try:
   11     import Tkinter as tk
   12 except ImportError:
   13     import tkinter as tk
   14 
   15 try:
   16     import ttk
   17     py3 = False
   18 except ImportError:
   19     import tkinter.ttk as ttk
   20     py3 = True
   21 
   22 import unknown_support
   23 
   24 def vp_start_gui():
   25     '''Starting point when module is the main routine.'''
   26     global val, w, root
   27     root = tk.Tk()
   28     top = Toplevel1 (root)
   29     unknown_support.init(root, top)
   30     root.mainloop()
   31 
   32 w = None
   33 def create_Toplevel1(rt, *args, **kwargs):
   34     '''Starting point when module is imported by another module.
   35        Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
   36     global w, w_win, root
   37     #rt = root
   38     root = rt
   39     w = tk.Toplevel (root)
   40     top = Toplevel1 (w)
   41     unknown_support.init(w, top, *args, **kwargs)
   42     return (w, top)
   43 
   44 def destroy_Toplevel1():
   45     global w
   46     w.destroy()
   47     w = None
   48 
   49 class Toplevel1:
   50     def __init__(self, top=None):
   51         '''This class configures and populates the toplevel window.
   52            top is the toplevel containing window.'''
   53         _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
   54         _fgcolor = '#000000'  # X11 color: 'black'
   55         _compcolor = '#d9d9d9' # X11 color: 'gray85'
   56         _ana1color = '#d9d9d9' # X11 color: 'gray85'
   57         _ana2color = '#ececec' # Closest X11 color: 'gray92'
   58 
   59         top.geometry("600x450+817+281")
   60         top.minsize(120, 1)
   61         top.maxsize(1924, 1061)
   62         top.resizable(1,  1)
   63         top.title("New Toplevel")
   64         top.configure(background="#d9d9d9")
   65         top.configure(highlightbackground="#d9d9d9")
   66         top.configure(highlightcolor="black")
   67 
   68         self.Button1 = tk.Button(top)
   69         self.Button1.place(relx=0.483, rely=0.267, height=24, width=177)
   70         self.Button1.configure(activebackground="#ececec")
   71         self.Button1.configure(activeforeground="#000000")
   72         self.Button1.configure(background="#d9d9d9")
   73         self.Button1.configure(disabledforeground="#a3a3a3")
   74         self.Button1.configure(foreground="#000000")
   75         self.Button1.configure(highlightbackground="#d9d9d9")
   76         self.Button1.configure(highlightcolor="black")
   77         self.Button1.configure(pady="0")
   78         self.Button1.configure(text='''Send friend request''')
   79 
   80         self.Profile_Picture = tk.Canvas(top)
   81         self.Profile_Picture.place(relx=0.033, rely=0.044, relheight=0.273
   82                 , relwidth=0.322)
   83         self.Profile_Picture.configure(background="#d9d9d9")
   84         self.Profile_Picture.configure(borderwidth="2")
   85         self.Profile_Picture.configure(highlightbackground="#d9d9d9")
   86         self.Profile_Picture.configure(highlightcolor="black")
   87         self.Profile_Picture.configure(insertbackground="black")
   88         self.Profile_Picture.configure(relief="ridge")
   89         self.Profile_Picture.configure(selectbackground="blue")
   90         self.Profile_Picture.configure(selectforeground="white")
   91 
   92         self.Label1 = tk.Label(top)
   93         self.Label1.place(relx=0.533, rely=0.044, height=21, width=84)
   94         self.Label1.configure(activebackground="#f9f9f9")
   95         self.Label1.configure(activeforeground="black")
   96         self.Label1.configure(background="#d9d9d9")
   97         self.Label1.configure(disabledforeground="#a3a3a3")
   98         self.Label1.configure(foreground="#000000")
   99         self.Label1.configure(highlightbackground="#d9d9d9")
  100         self.Label1.configure(highlightcolor="black")
  101         self.Label1.configure(text='''Username''')
  102 
  103         self.Canvas1 = tk.Canvas(top)
  104         self.Canvas1.place(relx=0.067, rely=0.356, relheight=0.607
  105                 , relwidth=0.788)
  106         self.Canvas1.configure(background="#d9d9d9")
  107         self.Canvas1.configure(borderwidth="2")
  108         self.Canvas1.configure(highlightbackground="#d9d9d9")
  109         self.Canvas1.configure(highlightcolor="black")
  110         self.Canvas1.configure(insertbackground="black")
  111         self.Canvas1.configure(relief="ridge")
  112         self.Canvas1.configure(selectbackground="blue")
  113         self.Canvas1.configure(selectforeground="white")
  114 
  115         self.Labelframe1 = tk.LabelFrame(top)
  116         self.Labelframe1.place(relx=0.4, rely=0.089, relheight=0.167
  117                 , relwidth=0.517)
  118         self.Labelframe1.configure(relief='groove')
  119         self.Labelframe1.configure(foreground="black")
  120         self.Labelframe1.configure(text='''Biography''')
  121         self.Labelframe1.configure(background="#d9d9d9")
  122         self.Labelframe1.configure(highlightbackground="#d9d9d9")
  123         self.Labelframe1.configure(highlightcolor="black")
  124 
  125 if __name__ == '__main__':
  126     vp_start_gui()
  127 
  128 

