    1 #! /usr/bin/env python
    2 #  -*- coding: utf-8 -*-
    3 #
    4 # Support module generated by PAGE version 6.0.1
    5 #  in conjunction with Tcl version 8.6
    6 #    Jan 09, 2021 03:23:51 PM EST  platform: Windows NT
    7 
    8 import sys
    9 
   10 try:
   11     import Tkinter as tk
   12 except ImportError:
   13     import tkinter as tk
   14 
   15 try:
   16     import ttk
   17     py3 = False
   18 except ImportError:
   19     import tkinter.ttk as ttk
   20     py3 = True
   21 
   22 def init(top, gui, *args, **kwargs):
   23     global w, top_level, root
   24     w = gui
   25     top_level = top
   26     root = top
   27 
   28 def destroy_window():
   29     # Function which closes the window.
   30     global top_level
   31     top_level.destroy()
   32     top_level = None
   33 
   34 if __name__ == '__main__':
   35     import unknown
   36     unknown.vp_start_gui()
   37 
   38 
